//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Camps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Camps() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Camps", typeof(Camps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to delete the camp \n\n{0}\n\nAre you sure?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string DetailsBackToList {
            get {
                return ResourceManager.GetString("DetailsBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DetailsDelete {
            get {
                return ResourceManager.GetString("DetailsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DetailsEdit {
            get {
                return ResourceManager.GetString("DetailsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp information.
        /// </summary>
        public static string DetailsLegend {
            get {
                return ResourceManager.GetString("DetailsLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string EditAdd {
            get {
                return ResourceManager.GetString("EditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string EditBackToList {
            get {
                return ResourceManager.GetString("EditBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp information edit.
        /// </summary>
        public static string EditLegend {
            get {
                return ResourceManager.GetString("EditLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New camp.
        /// </summary>
        public static string EditNew {
            get {
                return ResourceManager.GetString("EditNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Required fields.
        /// </summary>
        public static string EditRequiredFields {
            get {
                return ResourceManager.GetString("EditRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string EditSaving {
            get {
                return ResourceManager.GetString("EditSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new....
        /// </summary>
        public static string IndexCreateNew {
            get {
                return ResourceManager.GetString("IndexCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string IndexDelete {
            get {
                return ResourceManager.GetString("IndexDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string IndexEdit {
            get {
                return ResourceManager.GetString("IndexEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camps by Year.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camps.
        /// </summary>
        public static string MainMenuItem {
            get {
                return ResourceManager.GetString("MainMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string ModelBeginDate {
            get {
                return ResourceManager.GetString("ModelBeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ModelDescription {
            get {
                return ResourceManager.GetString("ModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string ModelEndDate {
            get {
                return ResourceManager.GetString("ModelEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ModelHistory {
            get {
                return ResourceManager.GetString("ModelHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ModelTheme {
            get {
                return ResourceManager.GetString("ModelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
    }
}
