//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Campers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Campers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Campers", typeof(Campers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to delete the camper \n\n{0}\n\nAre you sure?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string DetailsBackToList {
            get {
                return ResourceManager.GetString("DetailsBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM-dd-yyyy}.
        /// </summary>
        public static string DetailsBirthdateFormat {
            get {
                return ResourceManager.GetString("DetailsBirthdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DetailsDelete {
            get {
                return ResourceManager.GetString("DetailsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DetailsEdit {
            get {
                return ResourceManager.GetString("DetailsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camper profile.
        /// </summary>
        public static string DetailsLegend {
            get {
                return ResourceManager.GetString("DetailsLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string EditAdd {
            get {
                return ResourceManager.GetString("EditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string EditBackToList {
            get {
                return ResourceManager.GetString("EditBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:MM-dd-yyyy}.
        /// </summary>
        public static string EditBirthdateFormat {
            get {
                return ResourceManager.GetString("EditBirthdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camper profile edit.
        /// </summary>
        public static string EditLegend {
            get {
                return ResourceManager.GetString("EditLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New camper.
        /// </summary>
        public static string EditNew {
            get {
                return ResourceManager.GetString("EditNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Required fields.
        /// </summary>
        public static string EditRequiredFields {
            get {
                return ResourceManager.GetString("EditRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string EditSaving {
            get {
                return ResourceManager.GetString("EditSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New....
        /// </summary>
        public static string IndexCreateNew {
            get {
                return ResourceManager.GetString("IndexCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string IndexDelete {
            get {
                return ResourceManager.GetString("IndexDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string IndexEdit {
            get {
                return ResourceManager.GetString("IndexEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campers.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Note.
        /// </summary>
        public static string ModelAddressNote {
            get {
                return ResourceManager.GetString("ModelAddressNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appartment Number.
        /// </summary>
        public static string ModelAppartmentNumber {
            get {
                return ResourceManager.GetString("ModelAppartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ModelCity {
            get {
                return ResourceManager.GetString("ModelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string ModelCityId {
            get {
                return ResourceManager.GetString("ModelCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string ModelComments {
            get {
                return ResourceManager.GetString("ModelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least one phone number.
        /// </summary>
        public static string ModelCommentsRequired {
            get {
                return ResourceManager.GetString("ModelCommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ModelContacts {
            get {
                return ResourceManager.GetString("ModelContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string ModelDateOfBirth {
            get {
                return ResourceManager.GetString("ModelDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability Grade.
        /// </summary>
        public static string ModelDisabilityGrade {
            get {
                return ResourceManager.GetString("ModelDisabilityGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string ModelDistrict {
            get {
                return ResourceManager.GetString("ModelDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string ModelEmail {
            get {
                return ResourceManager.GetString("ModelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ModelFirstName {
            get {
                return ResourceManager.GetString("ModelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ModelFullName {
            get {
                return ResourceManager.GetString("ModelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Number.
        /// </summary>
        public static string ModelHomeNumber {
            get {
                return ResourceManager.GetString("ModelHomeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone.
        /// </summary>
        public static string ModelHomePhone {
            get {
                return ResourceManager.GetString("ModelHomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ModelLastName {
            get {
                return ResourceManager.GetString("ModelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Note.
        /// </summary>
        public static string ModelMedicalNote {
            get {
                return ResourceManager.GetString("ModelMedicalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Index.
        /// </summary>
        public static string ModelPostIndex {
            get {
                return ResourceManager.GetString("ModelPostIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string ModelSkype {
            get {
                return ResourceManager.GetString("ModelSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string ModelStreet {
            get {
                return ResourceManager.GetString("ModelStreet", resourceCulture);
            }
        }
    }
}
