//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Drivers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Drivers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Drivers", typeof(Drivers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are going to delete the driver\n\n{0}\n\nAre you sure?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string DetailsBackToList {
            get {
                return ResourceManager.GetString("DetailsBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DetailsEdit {
            get {
                return ResourceManager.GetString("DetailsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver profile.
        /// </summary>
        public static string DetailsLegend {
            get {
                return ResourceManager.GetString("DetailsLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string EditAdd {
            get {
                return ResourceManager.GetString("EditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string EditBackToList {
            get {
                return ResourceManager.GetString("EditBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver profile edit.
        /// </summary>
        public static string EditLegend {
            get {
                return ResourceManager.GetString("EditLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New driver.
        /// </summary>
        public static string EditNew {
            get {
                return ResourceManager.GetString("EditNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Required fields.
        /// </summary>
        public static string EditRequiredFields {
            get {
                return ResourceManager.GetString("EditRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditSave {
            get {
                return ResourceManager.GetString("EditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string EditSaving {
            get {
                return ResourceManager.GetString("EditSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New....
        /// </summary>
        public static string IndexCreateNew {
            get {
                return ResourceManager.GetString("IndexCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string IndexDelete {
            get {
                return ResourceManager.GetString("IndexDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string IndexEdit {
            get {
                return ResourceManager.GetString("IndexEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string ModelComments {
            get {
                return ResourceManager.GetString("ModelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ModelContacts {
            get {
                return ResourceManager.GetString("ModelContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ModelFirstName {
            get {
                return ResourceManager.GetString("ModelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ModelFullName {
            get {
                return ResourceManager.GetString("ModelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ModelLastName {
            get {
                return ResourceManager.GetString("ModelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sit Places.
        /// </summary>
        public static string ModelSitPlacesNum {
            get {
                return ResourceManager.GetString("ModelSitPlacesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheelchairs.
        /// </summary>
        public static string ModelWheelchairsNum {
            get {
                return ResourceManager.GetString("ModelWheelchairsNum", resourceCulture);
            }
        }
    }
}
